INHERIT: .config/copier/mkdocs.yaml
site_name: Quant on Crypto
site_description: TODO

plugins:
  mkdocstrings:
    handlers:
      python:
        inventories:
          - https://docs.python.org/3/objects.inv
