# 数据配置
data:
  trading_folder_path: "./data/5m_klines/"
  trading_raw_folder_path: "./data/5m_klines_n/"
  trading_freq: "5m" # K线频率

  marketsimu_folder_path: "./data/1m_klines/"
  marketsimu_raw_folder_path: "./data/1m_klines_n/"
  marketsimu_freq: "1m" # K线频率

# 回测配置
backtest:
  start_time: 1738368000000 # 101
  end_time: 1739606400000
  initial_capital: 10000 # 初始资金
  trading_fee: 0.0005 # 交易手续费率
output_path: "output" # 日志和结果输出路径

# 策略配置
strategy:
  name: "StatArbitrage"
  feature_params:
    regression_window: 50 # 回归窗口长度
    lookback_period: 300 # 回溯步数（一天的5分钟K线数量）
    std_rate: 0.005 # std_temp = np.sqrt(std_temp**2 * 0.99 + residual**2 * 0.01)
  trading_params:
    max_std: 0.1 # 最大波动率限制
    sigma_threshold: 2 # 残差偏离标准差的倍数阈值
    sigma_threshold_u: 4 # 残差偏离标准差的倍数阈值
    lc_threshold: -0.99 # 止损
    holding_period: 60 # 最大持有时间（以K线数量计）

    order_time: 3
