
# 数据配置
data:
  folder_path: "/Users/lizeyu/Downloads/Quant-on-Crypto/data/5m_klines_n/"  # K线数据文件夹路径
  raw_folder_path: "/Users/lizeyu/Downloads/Quant-on-Crypto/data/5m_klines/"  # K线数据文件夹路径
  freq: "5m"  # K线频率

# 回测配置
backtest:
  # start_time: 1715851200000  # 回测起始时间 (Unix timestamp in milliseconds)
  # end_time:   1730360700000    # 回测结束  
  start_time: 1704038400000  # 101
  
  # start_time: 1735756800000
  # start_time: 1707955200000  # 215
  # end_time:   1709568000000    # 305
  # end_time:   1709568000000    # 305
  # start_time:   1715904000000    # 515
  # end_time:     1725148800000   # 901
  end_time:       1746057000000
  # end_time:       1739558400000
  # end_time:     1725148800000   # 901
  d_t: 300000 # 5分钟 = 300000毫秒
  initial_capital: 10000      # 初始资金
  trading_fee: 0.0005            # 交易手续费率
output_path: "output"  # 日志和结果输出路径

# 策略配置
strategy:
  name: "StatArbitrage"
  # feature_params: #305-515
  #   regression_window: 400         # 回归窗口长度
  #   lookback_period: 800          # 回溯步数（一天的5分钟K线数量）
  #   std_rate: 0.01                # std_temp = np.sqrt(std_temp**2 * 0.99 + residual**2 * 0.01)
  # trading_params:
  #   correlation_threshold_u: 1        # 相关性上限要求
  #   max_std: 0.1                  # 最大波动率限制
  #   sigma_threshold: 2          # 残差偏离标准差的倍数阈值
  #   sigma_threshold_u: 4         # 残差偏离标准差的倍数阈值
  #   lc_threshold: -0.05           # 止损
  #   holding_period: 300            # 最大持有时间（以K线数量计）
  #   freeze_period: 1440             # 冻结期（以K线数量计）  
  feature_params:
    regression_window: 50         # 回归窗口长度
    lookback_period: 300          # 回溯步数（一天的5分钟K线数量）
    std_rate: 0.005                # std_temp = np.sqrt(std_temp**2 * 0.99 + residual**2 * 0.01)
  trading_params:
    correlation_threshold_u: 1        # 相关性上限要求
    max_std: 0.1                  # 最大波动率限制
    sigma_threshold: 2          # 残差偏离标准差的倍数阈值
    sigma_threshold_u: 4         # 残差偏离标准差的倍数阈值
    lc_threshold: -0.99           # 止损
    holding_period: 60            # 最大持有时间（以K线数量计）
    freeze_period: 1440             # 冻结期（以K线数量计）

  # feature_params:
  #   regression_window: 50         # 回归窗口长度
  #   lookback_period: 300          # 回溯步数（一天的5分钟K线数量）
  #   std_rate: 0.005                # std_temp = np.sqrt(std_temp**2 * 0.99 + residual**2 * 0.01)
  # trading_params:
  #   correlation_threshold_u: 1        # 相关性上限要求
  #   max_std: 0.1                  # 最大波动率限制
  #   sigma_threshold: 2          # 残差偏离标准差的倍数阈值
  #   sigma_threshold_u: 4         # 残差偏离标准差的倍数阈值
  #   lc_threshold: -0.02           # 止损
  #   holding_period: 30            # 最大持有时间（以K线数量计）
  #   freeze_period: 1440             # 冻结期（以K线数量计）

