# 数据相关配置
data_dir: "data/5m_klines"      # 文件夹路径（小量测试）
file_suffix: "_klines_5m.csv"          # 文件后缀
min_csv_length: 10000                  # 最小 CSV 行数

# 回归与策略参数
window_size: 50                        # 回归窗口长度
past_length: 288                       # 回溯步数
window_corr: 864                       # 窗口相关性长度（PAST_LENGTH * 3）
thres: 2                               # 偏离 sigma 倍数
zs: -0.03                              # Z 分数阈值
hold_time: 30                          # 持有时间
fee: 0                                 # 手续费
corr_threshold: 0.5                    # 相关性阈值
std_max_threshold: 0.1                # 标准差最大阈值
freeze_period_threshold: 288          # 冻结期阈值

# 可视化与输出设置
visualize_input: true                 # 可视化输入数据
visualize_statics: true              # 可视化中间数据
visualize_output: true               # 可视化输出数据

# 输出设置
output_path: "output"                 # 输出路径
